update build and fix exec

diff --git a/config.yml b/config.yml
--- a/config.yml
+++ b/config.yml
@@ -32,26 +32,26 @@ customCommands:
   - name: 💡 Logs regex
     command: |
       echo "" | fzf --reverse --bind "result:last" --disabled \
-      --bind "start:reload(docker  logs $COMPOSE_SERVICE_NAME --timestamps 2>&1 | tspin | rg --smart-case --color=always {q})" \
-      --bind "change:reload(docker logs $COMPOSE_SERVICE_NAME --timestamps 2>&1 | tspin | rg --smart-case --color=always {q} || echo '⚠️ Invalid regex pattern')"
+        --bind "start:reload(docker  logs $COMPOSE_SERVICE_NAME --timestamps 2>&1 | tspin | rg --smart-case --color=always {q})" \
+        --bind "change:reload(docker logs $COMPOSE_SERVICE_NAME --timestamps 2>&1 | tspin | rg --smart-case --color=always {q} || echo '⚠️ Invalid regex pattern')"
     attach: false
-  - name: "{} Logs json"
+  - name: 💬 Logs json
     command: docker logs $COMPOSE_SERVICE_NAME --follow 2>&1 | while read -r line; do echo $line | jq -cC; done | fzf --reverse --bind "result:last" --exact
     attach: false
-  - name: $_ Sh
-    command: docker-compose exec $COMPOSE_SERVICE_NAME 'sh'
+  - name: 💻 Sh
+    command: docker-compose exec $COMPOSE_SERVICE_NAME sh
     attach: false
   - name: 🔑 Bash root
-    command: docker-compose exec -u root $COMPOSE_SERVICE_NAME 'bash'
+    command: docker-compose exec -u root $COMPOSE_SERVICE_NAME bash
     attach: false
   - name: 📊 top
     command: docker-compose top
     attach: true
   - name: 🏔️ Alpine htop
-    command: docker-compose exec $COMPOSE_SERVICE_NAME sh -c 'apk add htop && htop'
+    command: docker-compose exec $COMPOSE_SERVICE_NAME sh -c 'apk add --no-cache htop && htop'
     attach: false
   - name: 🌀 Debian htop
-    command: docker-compose exec $COMPOSE_SERVICE_NAME sh -c 'apt install -y htop && htop'
+    command: docker-compose exec $COMPOSE_SERVICE_NAME sh -c 'apt update && apt install -y htop && htop'
     attach: false
   - name: 🌐 Web links
     command: IP=$(hostname -I | awk '{print $1}'); docker port $COMPOSE_SERVICE_NAME | awk -F ':' -v ip="$IP" '$2!="" {print "http://"ip":"$2}' | sort -u
@@ -59,31 +59,31 @@ customCommands:
   - name: 🏷️ Inspect config labels
     command: |
       echo "" | fzf --reverse --disabled --query ".[].Config.Labels" \
-      --bind "start:reload(docker inspect $COMPOSE_SERVICE_NAME | jq -C {q})" \
-      --bind "change:reload(docker inspect $COMPOSE_SERVICE_NAME | jq -C {q} || echo -e '⚠️ Invalid query filter')"
+        --bind "start:reload(docker inspect $COMPOSE_SERVICE_NAME | jq -C {q})" \
+        --bind "change:reload(docker inspect $COMPOSE_SERVICE_NAME | jq -C {q} || echo -e '⚠️ Invalid query filter')"
     attach: false
   - name: 📂 Diff files
     command: |
       clear && docker diff $COMPOSE_SERVICE_NAME | sed \
-      -e "s/^A /$(printf '\033[32mA\033[0m ')/" \
-      -e "s/^C /$(printf '\033[33mC\033[0m ')/" \
-      -e "s/^D /$(printf '\033[31mD\033[0m ')/"
+        -e "s/^A /$(printf '\033[32mA\033[0m ')/" \
+        -e "s/^C /$(printf '\033[33mC\033[0m ')/" \
+        -e "s/^D /$(printf '\033[31mD\033[0m ')/"
     attach: true
   - name: 📋 Copy files
     command: |
       docker cp $COMPOSE_SERVICE_NAME:$FILE ./
       FILES=$(docker-compose exec $COMPOSE_SERVICE_NAME find / -type f | fzf --reverse --multi --exact)
       if [ -n "$FILES" ]; then
-          echo "$FILES" | while read -r FILE; do
-              docker cp $COMPOSE_SERVICE_NAME:"$FILE" ./
-          done
+        echo "$FILES" | while read -r FILE; do
+          docker cp $COMPOSE_SERVICE_NAME:"$FILE" ./
+        done
       fi && read
     attach: false
   - name: 🐳 Dockerfile edit
     command: find $(dirname $COMPOSE_FILE) -maxdepth 1 -iname *dockerfile* | head -n 1 | xargs micro
     attach: false
   - name: 🔨 Build image
-    command: docker-compose up -d --force-recreate --build $COMPOSE_SERVICE_NAME
+    command: TARGETARCH=$(docker version -f {{.Server.Arch}}) docker-compose up -d --build $COMPOSE_SERVICE_NAME
     attach: true
   - name: 📮 Images delete
     command: |
